GET https://relatoria.jep.gov.co/savedocumentreactions?providencia_id=3313&like=true HTTP/1.1
user: {{$dotenv REACT_APP_API_USER}}
password: {{$dotenv REACT_APP_API_PASS}}
Authorization: Bearer {{$dotenv REACT_APP_API_ACCESS_TOKEN}}
Content-Type: application/json

{

}