GET https://relatoria.jep.gov.co/searchqdata HTTP/1.1
user: {{$dotenv REACT_APP_API_USER}}
password: {{$dotenv REACT_APP_API_PASS}}
Authorization: Bearer {{$dotenv REACT_APP_API_ACCESS_TOKEN}}
Content-Type: application/json

{
    "string": "Necesito encontrar una providencia en la que se hable de la responsabilidad penal del señor Pastor Alape"
}